name: Rust CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  find-dirs:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.find.outputs.dirs }}
    steps:
      - uses: actions/checkout@v4
      - id: find
        run: |
          DIRS=$(find . -name "Cargo.toml" -type f | xargs dirname | sort | uniq | jq -R -s 'split("\n") | map(select(. != ""))')
          echo "dirs<<EOF" >> $GITHUB_OUTPUT
          echo "$DIRS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  check:
    needs: find-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.find-dirs.outputs.dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup upgrade
      - run: cargo check

  test:
    needs: find-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.find-dirs.outputs.dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup upgrade
      - run: cargo test
